version: 2.1

jobs:
  build-and-push:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build image"
          command: docker build -t blog .
      - run:
          name: "Tag image"
          command: docker tag blog eu.gcr.io/$GOOGLE_PROJECT_ID/blog
      - run:
          name: "Auth to gcloud for gcr"
          command: echo $GCLOUD_SERVICE_KEY > auth.json & gcloud auth activate-service-account $GCLOUD_ACOUNT_EMAIL --key-file=auth.json & gcloud auth configure-docker
      - run:
          name: "Auth to gcr"
          command: cat auth.json | docker login -u _json_key --password-stdin https://eu.gcr.io
      - run:
          name: "Push image"
          command: docker push eu.gcr.io/$GOOGLE_PROJECT_ID/blog
      - run:
          name: "Auth to gcloud for compute"
          command: echo $GCLOUD_COMPUTE_SERVICE_KEY > auth.json & gcloud auth activate-service-account --key-file=auth.json
      - run:
          name: "Deploy image"
          command: gcloud run deploy blog --project $GOOGLE_PROJECT_ID --image eu.gcr.io/$GOOGLE_PROJECT_ID/blog:latest  --region europe-west9 
      - run:
          name: "Flush images"
          command: ./flush-images.sh

workflows:
  deploy:
    jobs:
      - build-and-push:
          filters:
            branches:
              only:
                - master
          context:
            - blog
